trigger:
  batch: true
  branches:
    include:
    - main

pool: 'MyComputerAgent'

variables:
- name: deploymentDefaultLocation
  value: westus3

jobs:
- job:
  steps:

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: deploy/main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deployToyManualsStorageAccount $(DeployToyManualsStorageAccount)